### ISSUE TITLE
дистрибутив не содержит файл Nebula.KeysGenerator 1.0.0.0.zip

### ISSUE THREAD

**Issue by rocketsan** [orangedata-official/API#2]
В Readme_v2.txt содержится информация о генераторе ключей Nebula.KeysGenerator. Но самого генератора в архиве нет. Дайте хотя бы прямую ссылку для скачивания.

**Comment by hats** [comment]
@rocketsan на самом деле, вы можете самостоятельно сгенерировать все, что вам надо. Инструкции по генерации можно прочитать [тут](https://github.com/hats/orange-data-client-ruby#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5).

**Comment by avbogdanov** [comment]
Nebula.KeysGenerator опубликован на gitlab:
https://github.com/orangedata-official/API/blob/master/Nebula.KeysGenerator-1.2.0.0.zip
