### ISSUE TITLE
Подпись не прошла проверку

### ISSUE THREAD

**Issue by greendankam** [orangedata-official/API#7]
Добрый день.
Пытаюсь выполнить ваш тестовый пример C#, используя тестовые сертификаты и ключ из архива file_for_test
Запрос:
uri = "https://apip.orangedata.ru:2443/api/v2/documents/"
json:
`{"Id":"5a8b6aa1-040a-45a5-b038-5d8ebf23be81","INN":"5001104058","Content":{"Type":1,"Positions":[{"Quantity":1.0,"Price":123.45,"Tax":6,"Text":"Булка","PaymentMethodType":4,"PaymentSubjectType":1},{"Quantity":2.0,"Price":4.45,"Tax":4,"Text":"Спички","PaymentMethodType":4,"PaymentSubjectType":1}],"CheckClose":{"Payments":[{"Type":1,"Amount":132.35}],"TaxationSystem":1},"CustomerContact":"foo@example.com","AgentType":2}}`
Подпись:
`sbz+qaRGi8Qybaoivqv10qbPMI0EJB97JCO0sfJHxYmJlIbJLhXGh81zZF72bo2/WmEms02szpwv3zOpBGi4R9Mp+xqNgS3QJFjH8ps5ojBMELPE82tYyMxwd1pBFXlIUDVF3yR2QAQJYMA1nMYVG/YFY4cQTPND5q3jl46QiuD6BYjgoyKpa6fQJfBxnvzx8L1UKcx7ruKff75KipRupaRfOrLK3kQaImrV67yczOd9+xBTEIwxwkQx25sriCojR73rz1DGBwpAgwL2T+oDSZhmyvQnjwy3WH34plyWbhWjp1H3J7ctcLjBxAoBsLqSzLRuTVmBKkD/vtcZTMs/oQ==`
В ответ упорно ловлю 400-ую:
"{\"errors\":[\"Подпись не прошла проверку\"]}"
Что я делаю не так? Мб устарели ваши файлики?

**Comment by kodolex** [comment]
Аналогичная проблема.

**Comment by greendankam** [comment]
> Аналогичная проблема.

Получил ответ от их ТП
Надо во-первых использовать свой ИНН, во-вторых указывать в джейсоне ключ (Key) равным ИНН
"INN":"ваш инн", "Key":"ваш инн"
у меня сработало
кстати, очень быстро ответили, молодцы)

**Comment by timur-akanaev** [comment]
Да, ребята из поддержки молодцы!
Удачи вам, будем с вами работать и дальше
