### ISSUE TITLE
На тестовой среде тестовый ключ и сертификат не проходят проверку

### ISSUE THREAD

**Issue by Anat56** [orangedata-official/API#8]
При тестировании возвращается:
{
  "errors": [
    "Подпись не прошла проверку"
  ]
}
Использую библиотеку для C# и сертификаты https://github.com/orangedata-official/API/blob/master/File_for_test.zip

**Comment by avbogdanov** [comment]
Добрый день, Анатолий!
Issue в Гитхаб у нас не используются.  Извините, только сейчас увидели Ваше сообщение.  По проблемам с кодом пожалуйста пишите в техподдержку на адрес support@orangedata.ru
